<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Current Address_currentAddress</name>
   <tag></tag>
   <elementGuidId>37393b48-d258-45d8-9a7b-746d3904c1c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currentAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='currentAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f677ccf9-ef55-46f4-b7a7-8d1f4f57d820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Address</value>
      <webElementGuid>ab0aabec-0bb5-473b-917b-359f02baa86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ecb63683-b297-47eb-86b5-9b9280f7a55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>95855b09-6fd3-4d55-91bf-a9976a106f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentAddress</value>
      <webElementGuid>b39795a6-e742-4322-8c4a-8a1b8d174c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb21cc0f-a19c-42f1-b54b-36cca791ac80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentAddress&quot;)</value>
      <webElementGuid>c156724e-d4bf-4268-bbb5-e7ce21b6a3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='currentAddress']</value>
      <webElementGuid>aa921df5-ffee-4732-9a40-fcb82365cb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>69f417c6-c0bf-4211-8791-7bde73178772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Address'])[1]/following::textarea[1]</value>
      <webElementGuid>495b8aa5-389d-43c7-b40e-a37f20c550c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::textarea[1]</value>
      <webElementGuid>0c8d2b36-7d35-4509-a064-e6fa4dc67975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Address'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4351c8d9-b740-4372-9cba-cfffdbc2b5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[2]</value>
      <webElementGuid>1a1ab22c-bcbb-4428-909c-002c69773c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>831b43c6-2db8-4fb3-846e-640f9d25553b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Current Address' and @id = 'currentAddress']</value>
      <webElementGuid>7c4a632e-a84a-43a7-8acc-dbb0d32744cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
