<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bad Request</name>
   <tag></tag>
   <elementGuidId>cae1dcb6-951d-4bfa-ab80-771a7e9c798d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bad-request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bad-request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2ee22b0-9a5c-4bb6-920e-93c8761e0718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bad-request</value>
      <webElementGuid>fdb3837d-33ac-45ae-9873-bd63a2641c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>beb44c7e-b275-4291-91c5-9b74d4f45350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bad Request</value>
      <webElementGuid>e21b3a3d-4cde-4b70-a72a-34e22c8ac7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bad-request&quot;)</value>
      <webElementGuid>9a77e6d5-e876-4b3f-b3d1-f6e79aaf849a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bad-request']</value>
      <webElementGuid>bc119bb3-9446-4d09-ae06-6072ace59c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[6]/a</value>
      <webElementGuid>dd42116e-af88-4a43-aeab-eb89c2d70f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bad Request')]</value>
      <webElementGuid>929305e0-ef28-46a5-a47d-6397cad44083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moved'])[1]/following::a[1]</value>
      <webElementGuid>f9d3221f-dfb6-4086-ae80-81d8badcbf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Content'])[1]/following::a[2]</value>
      <webElementGuid>348a22f9-35bc-4928-89e8-0d4081977ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unauthorized'])[1]/preceding::a[1]</value>
      <webElementGuid>8365db7a-f515-4f37-8b27-545a433df585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forbidden'])[1]/preceding::a[2]</value>
      <webElementGuid>26508f36-1e1d-41b3-899d-74fd814cc5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bad Request']/parent::*</value>
      <webElementGuid>9a81e10b-274f-4122-a2cd-6204d62f6faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>637e64de-22a3-4b64-8915-98a65ee65e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/a</value>
      <webElementGuid>418717b6-add2-4e59-bba5-300bcaacc16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bad-request' and @href = 'javascript:void(0)' and (text() = 'Bad Request' or . = 'Bad Request')]</value>
      <webElementGuid>ef5b9e97-5bf9-4beb-9e85-5f1ee82d8e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
