<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forbidden</name>
   <tag></tag>
   <elementGuidId>25d54036-0068-46b0-99a9-ecd280606327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forbidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forbidden']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8ff6736-1d32-4cf6-b5b6-778c158b9371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forbidden</value>
      <webElementGuid>df1ae7cf-53c3-4244-8efd-1217f3ed230a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>d1a91462-79f3-45c5-bf3f-c89d171899e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forbidden</value>
      <webElementGuid>dc59ddfc-912d-4102-b99f-5b82accc35a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forbidden&quot;)</value>
      <webElementGuid>b4f05570-fdc8-4382-9818-8d77d94b9951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forbidden']</value>
      <webElementGuid>e83bf533-1489-4f41-b383-998920c0da66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[8]/a</value>
      <webElementGuid>2ea3ab52-e10f-46b9-a366-8c74afb06d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forbidden')]</value>
      <webElementGuid>e8630cbe-8f77-4f0e-9db8-c2e9e83227f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unauthorized'])[1]/following::a[1]</value>
      <webElementGuid>42d78671-0ac6-4768-8ae0-740b02f9263e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bad Request'])[1]/following::a[2]</value>
      <webElementGuid>15b8b501-12ae-4425-9c96-cdba6069a110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Found'])[1]/preceding::a[1]</value>
      <webElementGuid>5f9dc7f1-2bd5-4244-bd8d-cc3eb8073587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::a[3]</value>
      <webElementGuid>bfa0642b-91e0-43dc-8174-a82d3d7cc62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forbidden']/parent::*</value>
      <webElementGuid>c52da109-9a68-4f0d-9699-3a78d10c2aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[6]</value>
      <webElementGuid>6534f016-23e5-4af8-9de6-39a5be6c9085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/a</value>
      <webElementGuid>77c69b8d-f99b-427a-a653-887061d07eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forbidden' and @href = 'javascript:void(0)' and (text() = 'Forbidden' or . = 'Forbidden')]</value>
      <webElementGuid>430c9d4e-f414-400b-94f8-f752d05bb217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
