<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No Content</name>
   <tag></tag>
   <elementGuidId>8246961d-99c6-479e-b54b-ff63c306d0f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='no-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffccbf9d-0640-4e2c-94de-76b10c97d9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no-content</value>
      <webElementGuid>49a3f202-c498-4ff8-a182-baf4e4f8eea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ceddf6f5-1b01-41e7-86ed-259f6e000e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Content</value>
      <webElementGuid>6b6350a1-e4b7-47d6-9f04-c34aa88a1404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no-content&quot;)</value>
      <webElementGuid>a31c4a18-9e44-4448-8338-6eb8f30a07f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='no-content']</value>
      <webElementGuid>c1ebe591-989e-43cd-b824-22e76fe7bc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[4]/a</value>
      <webElementGuid>8e7ecd50-8b34-45c1-b8d0-8e97908abdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'No Content')]</value>
      <webElementGuid>6849aa44-327e-4464-93c9-68e56d4f4e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::a[1]</value>
      <webElementGuid>881c3dbc-8ace-448e-b58e-f923b1bf9529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following links will send an api call'])[1]/following::a[2]</value>
      <webElementGuid>fa6640c1-bca1-4206-846a-0cd06520dd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moved'])[1]/preceding::a[1]</value>
      <webElementGuid>4159bd3d-0f99-4246-8c49-53d0452ecefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bad Request'])[1]/preceding::a[2]</value>
      <webElementGuid>6b68071b-15f3-476c-abb9-79313c1d5331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No Content']/parent::*</value>
      <webElementGuid>d827058e-2a74-4bb0-861d-5e023178d099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>eb9b9af9-cb6c-4bb5-8895-bd9da48d005e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>e5f78d68-54a0-40f9-8b4b-40f379f0a032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'no-content' and @href = 'javascript:void(0)' and (text() = 'No Content' or . = 'No Content')]</value>
      <webElementGuid>cce37a5b-ff88-4350-995b-e21b1348367e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
