<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unauthorized</name>
   <tag></tag>
   <elementGuidId>6332f6db-a409-4b26-b09e-388c870fb98c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unauthorized</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='unauthorized']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68f961a2-8778-438d-9583-00fc6803a120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unauthorized</value>
      <webElementGuid>632cd54e-1f30-47c7-8609-57e9bf2e68e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f16cf605-c375-4e0d-a591-284ae9293f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unauthorized</value>
      <webElementGuid>3532de1a-3afa-4bd9-957a-af0fa5630a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unauthorized&quot;)</value>
      <webElementGuid>2b46db9e-5d55-4f1e-9902-290a2b49cf46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='unauthorized']</value>
      <webElementGuid>42c03277-ab17-4c7b-8e48-3fe735f378f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[7]/a</value>
      <webElementGuid>9e382be2-3869-4476-80b5-c1c6fecb7380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unauthorized')]</value>
      <webElementGuid>f726a5e5-c2f1-4802-bec9-be39f8037586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bad Request'])[1]/following::a[1]</value>
      <webElementGuid>67d617e6-ccde-4545-9592-2c901c595267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moved'])[1]/following::a[2]</value>
      <webElementGuid>0a745b2f-b317-4ea0-af33-40a7463b07a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forbidden'])[1]/preceding::a[1]</value>
      <webElementGuid>741274dd-ffaa-4905-b267-871443aff655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Found'])[1]/preceding::a[2]</value>
      <webElementGuid>152f1fde-20bc-4880-8731-da6b96a77a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unauthorized']/parent::*</value>
      <webElementGuid>a32b9e0f-fa6f-4081-87b8-07c8b5ac1ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[5]</value>
      <webElementGuid>a3a4cd78-f4be-49d6-a32d-f933cbb22792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/a</value>
      <webElementGuid>97e697cd-81d6-4c8e-861c-41d3a6d9a3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'unauthorized' and @href = 'javascript:void(0)' and (text() = 'Unauthorized' or . = 'Unauthorized')]</value>
      <webElementGuid>4fbd6778-4515-4fcb-a05a-25e742fb0dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
