<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>created has responded with staus 201 and status text Created</name>
   <tag></tag>
   <elementGuidId>50793f2b-7b74-49b4-8101-070717e93fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkResponse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='linkResponse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6296da37-5c78-478e-8425-37ecbe613468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkResponse</value>
      <webElementGuid>0ee23129-4d9c-4b80-acbb-125906bbb990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link has responded with staus 201 and status text Created</value>
      <webElementGuid>64c5dd45-5f4c-4d1b-8a5a-78d039fdaaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkResponse&quot;)</value>
      <webElementGuid>75b65fa2-84ec-4dc0-bd12-a7666d7a578b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='linkResponse']</value>
      <webElementGuid>867e6631-d87d-49f2-bdb4-3fe201b453b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[10]</value>
      <webElementGuid>84d7281e-bae8-438e-a668-ed42c59127de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Found'])[1]/following::p[1]</value>
      <webElementGuid>3ab63765-2c65-4d1a-a6a6-69c1286034e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forbidden'])[1]/following::p[2]</value>
      <webElementGuid>f8e2b7c1-171b-4488-9ccb-0222aefc901b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>bf5b6f70-441c-4ddb-b7f8-3fe22cf47c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link has responded with staus']/parent::*</value>
      <webElementGuid>767717c8-c54b-4b22-87e0-9be033ec1132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]</value>
      <webElementGuid>c869128e-ce16-4e96-9a88-cd58066f44de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'linkResponse' and (text() = 'Link has responded with staus 201 and status text Created' or . = 'Link has responded with staus 201 and status text Created')]</value>
      <webElementGuid>269b1445-b27a-469d-9d16-b82d2d25a8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
