<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no content has responded with staus 204 and status text No Content</name>
   <tag></tag>
   <elementGuidId>c97de707-61e3-49da-90cb-434143bc6c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkResponse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='linkResponse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>29382e07-0a8e-483c-ab86-39d9fadc51ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkResponse</value>
      <webElementGuid>a2e809dd-73b9-4250-9623-58f9f2cd78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link has responded with staus 204 and status text No Content</value>
      <webElementGuid>80940be0-fb4b-45f9-96d6-ebd6b1a828b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkResponse&quot;)</value>
      <webElementGuid>249c3316-d134-4f92-9da8-770daf986bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='linkResponse']</value>
      <webElementGuid>ac92de04-3d2e-4360-8047-7c2917b0c486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[10]</value>
      <webElementGuid>7b1e5c5e-96d8-460c-957c-e67d9bfb299a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Found'])[1]/following::p[1]</value>
      <webElementGuid>1cb508d9-1376-488b-bb6a-a390ff6b3d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forbidden'])[1]/following::p[2]</value>
      <webElementGuid>50419700-4256-45a6-868f-56e2242ef913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>dcff4d12-f619-4266-92c5-86ed3544188f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link has responded with staus']/parent::*</value>
      <webElementGuid>b0859cfe-ccad-440d-b62a-c576bf5196fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]</value>
      <webElementGuid>1edb0660-8948-4e5d-987a-66b952e7bfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'linkResponse' and (text() = 'Link has responded with staus 204 and status text No Content' or . = 'Link has responded with staus 204 and status text No Content')]</value>
      <webElementGuid>81a24a18-6cf2-4148-b1b9-eac169168d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
