<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unauthorized has responded with staus 401 and status text Unauthorized</name>
   <tag></tag>
   <elementGuidId>0a091f18-dd3a-49e6-a728-45c80e1e603f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkResponse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='linkResponse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>57c3685e-7ca4-4b6d-9f00-6e79861f06b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkResponse</value>
      <webElementGuid>34ada20a-30a0-48d7-9ef0-86fc160d7ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link has responded with staus 401 and status text Unauthorized</value>
      <webElementGuid>bc1144d7-2b3e-4302-bdea-3049cca15c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkResponse&quot;)</value>
      <webElementGuid>60a4d3fb-b96c-4b26-9f11-a2552019e085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='linkResponse']</value>
      <webElementGuid>0f73eb39-d292-4446-80ba-ad212d41d38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[10]</value>
      <webElementGuid>05b8bd59-00e4-433c-abcf-395b5767747f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Found'])[1]/following::p[1]</value>
      <webElementGuid>aaaaa856-e13a-4958-b8d8-aa94f4009b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forbidden'])[1]/following::p[2]</value>
      <webElementGuid>4c259fc9-7dfe-46f0-840e-ef641132a045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>b8502d3c-6434-4586-a6c9-3c058a540202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link has responded with staus']/parent::*</value>
      <webElementGuid>8cfadf48-ee05-4250-9563-9beba123dbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]</value>
      <webElementGuid>6e33a10f-7eb4-41b6-8ca0-f903f5b95afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'linkResponse' and (text() = 'Link has responded with staus 401 and status text Unauthorized' or . = 'Link has responded with staus 401 and status text Unauthorized')]</value>
      <webElementGuid>1ddcaa0a-3594-48f7-aa07-33f1400adc99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
