<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button On button click, prompt box will appear</name>
   <tag></tag>
   <elementGuidId>36a9f5b2-cf5a-4c4d-9d47-62a5e18a477f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='promtButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8dae796a-e0da-426a-b308-3e212f93d670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705465889536</value>
      <webElementGuid>e5abad1e-bd49-4876-bb1b-5392cd8c8674</webElementGuid>
   </webElementProperties>
</WebElementEntity>
