<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button On button click, confirm box will appear</name>
   <tag></tag>
   <elementGuidId>baf5a130-9753-4181-a220-99d65499273c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>918e0d2c-95d7-4a7c-854a-78b3d12822ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705465864013</value>
      <webElementGuid>3cf38ac8-3036-4ecf-9aa2-f0896cdda164</webElementGuid>
   </webElementProperties>
</WebElementEntity>
