<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Click Button to see alert</name>
   <tag></tag>
   <elementGuidId>30676aab-15ba-4287-bd76-59c60d7da37c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alertButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1e568a9c-9769-4023-bf09-aec4ec40672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705465794900</value>
      <webElementGuid>8b57f8fb-38fe-430a-ae0e-0e1ce386c565</webElementGuid>
   </webElementProperties>
</WebElementEntity>
